export default {
  ribbons: [
    {
      bank: 'Primary Bank',
      account: '0000',
      amount: '0',
      bg: '#ffe8ec',
      bgEnd: '#c4dcff',
      text: '#173f7a',
      muted: '#5a6473',
      icon: '#1f4b8f',
      stripe: '#e31e2f',
      border: '#bfd0eb',
    },
    {
      bank: 'Salary Account',
      account: '0000',
      amount: '0',
      bg: '#0f4f99',
      bgEnd: '#3474be',
      text: '#ffffff',
      muted: 'rgba(255,255,255,0.78)',
      icon: '#ffffff',
      stripe: '#e31b23',
      border: '#0d4f93',
    },
    {
      bank: 'Savings',
      account: '0000',
      amount: '0',
      bg: '#f5f3ff',
      bgEnd: '#ddd6fe',
      text: '#312e81',
      muted: '#6366f1',
      icon: '#4338ca',
      stripe: '#7c3aed',
      border: '#c4b5fd',
    },
    {
      bank: 'Wallet',
      account: 'Cash',
      amount: '0',
      bg: '#f5ede3',
      bgEnd: '#caa27c',
      text: '#4b2e1f',
      muted: '#7a553c',
      icon: '#6b4226',
      stripe: '#8b5e3c',
      border: '#b08968',
    },
  ],
  creditCards: [{ name: 'Credit Card', amount: 0, note: 'Sample card' }],
  loanTrackerItems: [
    {
      id: 'loan-a',
      title: 'Loan A',
      lender: 'Sample loan',
      progress: 6 / 12,
      amountLeftValue: 120000,
      progressLabel: '6 months left',
      headline: '6 months left',
      amountLeft: '₹1,20,000',
      support: 'Monthly EMI ₹20,000',
      detailRows: [
        { label: 'Original amount', value: '₹2,40,000' },
        { label: 'Monthly EMI', value: '₹20,000' },
        { label: 'Next due', value: 'Sample date' },
      ],
      schedule: ['Month 1 - ₹20,000', 'Month 2 - ₹20,000', 'Month 3 - ₹20,000'],
    },
    {
      id: 'loan-b',
      title: 'Loan B',
      lender: 'Sample device plan',
      progress: 3 / 10,
      amountLeftValue: 35000,
      progressLabel: '7 months left',
      headline: '7 months left',
      amountLeft: '₹35,000',
      support: 'Monthly EMI ₹5,000',
      detailRows: [
        { label: 'Original amount', value: '₹50,000' },
        { label: 'Monthly EMI', value: '₹5,000' },
        { label: 'Next due', value: 'Sample date' },
      ],
      schedule: ['Month 1 - ₹5,000', 'Month 2 - ₹5,000', 'Month 3 - ₹5,000'],
    },
  ],
  peopleToGiveMoney: [
    { name: 'Person A', amount: 0 },
    { name: 'Person B', amount: 0 },
    { name: 'Person C', amount: 0 },
  ],
  financeTransactions: [],
  physicalHealth: {
    targets: { calories: 2200, protein: 150, carbs: 250, fats: 70, water: 3000, weight: 70 },
    foods: [
      { id: 'egg',             name: 'Egg (whole)',     kcal: 155, protein: 13,   carbs:  1.1, fats: 11   },
      { id: 'idli',            name: 'Idli',            kcal:  39, protein:  2,   carbs:  8,   fats:  0.2 },
      { id: 'dosa-plain',      name: 'Dosa (plain)',    kcal: 168, protein:  4,   carbs: 29,   fats:  5   },
      { id: 'coconut-chutney', name: 'Coconut chutney', kcal: 200, protein:  2,   carbs:  6,   fats: 19   },
      { id: 'sambar',          name: 'Sambar',          kcal:  57, protein:  3,   carbs:  8,   fats:  1.5 },
      { id: 'milk-whole',      name: 'Milk (whole)',    kcal:  61, protein:  3.2, carbs:  4.8, fats:  3.3 },
      { id: 'milk-toned',      name: 'Milk (toned)',    kcal:  50, protein:  3,   carbs:  5,   fats:  1.5 },
      { id: 'curd-whole',      name: 'Curd (whole)',    kcal:  60, protein:  3,   carbs:  5,   fats:  3   },
      { id: 'chicken-cooked',  name: 'Chicken (cooked)',kcal: 165, protein: 31,   carbs:  0,   fats:  3.6 },
      { id: 'chicken-curry',   name: 'Chicken curry',   kcal: 200, protein: 20,   carbs:  4,   fats: 12   },
      { id: 'roti',            name: 'Roti / Chapati',  kcal: 310, protein: 11,   carbs: 56,   fats:  4   },
      { id: 'rice-cooked',     name: 'Rice (cooked)',   kcal: 130, protein:  2.7, carbs: 28,   fats:  0.3 },
      { id: 'carrot',          name: 'Carrot',          kcal:  41, protein:  0.9, carbs: 10,   fats:  0.2 },
      { id: 'cucumber',        name: 'Cucumber',        kcal:  16, protein:  0.7, carbs:  4,   fats:  0.1 },
      { id: 'banana',          name: 'Banana',          kcal:  89, protein:  1.1, carbs: 23,   fats:  0.3 },
      { id: 'apple',           name: 'Apple',           kcal:  52, protein:  0.3, carbs: 14,   fats:  0.2 },
      { id: 'peanut',          name: 'Peanut',          kcal: 567, protein: 26,   carbs: 16,   fats: 49   },
      { id: 'oats-dry',        name: 'Oats (dry)',      kcal: 389, protein: 17,   carbs: 66,   fats:  7   },
      { id: 'paneer',          name: 'Paneer',          kcal: 265, protein: 18,   carbs:  1.2, fats: 21   },
      { id: 'almond',          name: 'Almond',          kcal: 579, protein: 21,   carbs: 22,   fats: 50   },
    ],
    daily: {},
  },
}
